
work_dir: ./work_dir/asl/msg3d_joint

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/asl-signs/train_data_joint.npy
  label_path: ./data/asl-signs/train_label.pkl
  # random_choose: False
  # random_shift: False
  # random_move: False
  # window_size: -1
  # normalization: False

test_feeder_args:
  data_path: ./data/asl-signs/val_data_joint.npy
  label_path: ./data/asl-signs/val_label.pkl 

# model
model: model.msg3d.Model
model_args:
  num_class: 250
  num_point: 50 # number of landmarks
  num_person: 1
  num_gcn_scales: 8
  num_g3d_scales: 8
  graph: graph.asl.AdjMatrixGraph

# optim
optimizer: SGD
nesterov: True # only works for SGD 
weight_decay: 0.0003
# weight_decay: 0.0005
base_lr: 0.05
step: [45, 55]

# training
num_worker: 0 # delete this when in kaggle
num_epoch: 20 # 65
device: 0
batch_size: 32
forward_batch_size: 16
test_batch_size: 32




